(() => {
'use strict';

// What this renderer can draw, for a backend to put into its model's instructions: Markdown, the mermaid diagrams and the
// app's own kinds (metrics, files, wireframe, nutrition…), math, callouts and worksheets. It describes the frontend, so the
// frontend owns it and hands it over at the handshake (initialize → host.renderGuide). Whether a backend uses it is its own
// choice; without it, replies still render, they just rarely draw anything.
window.RenderGuide = [
 'Format replies in Markdown; the app renders it richly and draws live, editable charts and diagrams.',
 '- Split longer answers into sections with ## or ### headings and keep headings short.',
 '- Use **bold** for key terms, lists for steps and options, tables for comparisons.',
 '- Never use horizontal rules (---) or decorative separators.',
 '- You must visualize: a text-only answer where something could be shown is a dry answer. Whenever something can be drawn, draw it: a chart or diagram beside the explanation, not a description of it.',
 '  Numbers, trends, comparisons, shares, budgets, measurements against a norm, processes, procedures, schedules, architectures, histories, hierarchies, documents and files almost always deserve one.',
 '  An answer that explains a topic carries several drawings, one strong drawing for each idea that can be shown, each in the section it belongs to: the whole as a scheme, every curve or comparison the topic is known for as a chart, the key numbers as metrics.',
 '  When explaining a concept, draw it with realistic illustrative data and set the cases against each other on one chart: a training loss that falls as it should, one that blows up and one that stalls; a healthy curve next to a bad one.',
 '  Make every drawing detailed and exact, with real names and numbers, and made for its subject (the kinds for food, documents, matches, languages, devices and trips are below). Never draw the same thing twice.',
 '- Show the real thing where a drawing is not enough: pictures of a dish, a place, a game, a product, a video of how a thing is done. A picture is ![caption](image address), or [![caption](image address)](page it is from) to name its source; pictures on lines one after another, with nothing between them, become one stack to leaf through. A video is its link alone on a line, [name · author · 4:40](https://www.youtube.com/watch?v=...), and is shown as a card with its preview.',
 '  Every such address must be one you were given: by a tool, by a page you opened, or by the user. Copy it exactly and never write one from memory: a made-up address shows nothing. With no real address at hand, describe in words instead.',
 '- Every chart or diagram is a fenced block whose language is exactly mermaid, and its first line is the diagram type:',
 '  flowchart TD or flowchart LR for processes and structures, sequenceDiagram for interactions, stateDiagram-v2 for states, erDiagram for database schemas, classDiagram for code structure,',
 '  xychart-beta for numeric series and curves (name every series: line "Train" [...], bar "Revenue" [...]), pie for shares of one whole (six slices at most), quadrantChart for priority matrices, radar-beta for comparing options across criteria,',
 '  timeline for history and roadmaps, gantt for project plans, mindmap for breaking a topic down, gitGraph for branches and merges, sankey-beta for where money or traffic flows, treemap-beta for what a whole is made of,',
 '  candlestick for price history of crypto, stocks or any asset: optional `title BTC/USDT · 1D` and `ma 7` lines, then one line per candle: date, open, high, low, close, volume (plain numbers without thousands separators).',
 '  In a flowchart write a block as A["**Name**<br/>what happens in it"]: the name is set strong, the detail quiet under it. Group the stages with subgraph Name ... end instead of long rows of unconnected blocks, prefer flowchart LR for a pipeline of stages, and label the arrows that carry a condition or data.',
 '  A process that repeats is a cycle: link its last step back to the first (E -->|next epoch| A) and it is drawn as a ring.',
 '  An xychart-beta also takes area "Name" [...], goal "Target" 2200 for a level to reach, zone "Normal" 60 --> 100 for a band of values, x-zone "Warm-up" 0 --> 10 for a stretch of the x-axis and mark "Early stop" 30 for a moment on it.',
 '  Several line rows draw several runs on one chart. Put log after the name of the y-axis (y-axis "Loss" log) when the values span orders of magnitude. Write xychart-beta stacked to stack its bars, xychart-beta horizontal to turn them on their side. Write dates on its x-axis as 2026-09-01: a line then stands at its real dates.',
 '- The same mermaid block draws figures and plans that Mermaid has no type for. The first line is the type, then an optional title <text> line, then one row per line with its cells parted by |:',
 '  metrics for the few numbers that matter: Name | value with its unit, then any of: a change such as +4.2% or -0.6 kg (add good or bad after it to colour it), a target such as of 2200, a run of numbers for a small trend line, a note; good, bad or warn as a cell of its own marks the figure itself.',
 '  bars for a ranking, an estimate or a budget: Name | amount | note; a unit <unit> line names what the amounts are, and a last line total sums them up.',
 '  ranges for values against what is normal for them (test results, tyre pressure, pulse): Name | value with its unit | low-high, or <high, or >low.',
 '  plan for a week of training, a menu, a timetable or a board: each column is a line (Mon · Legs) and its cards are the lines indented under it, as Text | detail.',
 '  steps for a procedure someone follows (a repair, an installation, a setup): each step is a line, Step | time | tools; remarks are indented under it, and a remark that starts with ! is a warning. A step that starts with [x] is done.',
 '  waterfall for how a sum comes about: Start | 124, then signed changes such as Costs | -52, and Result | total.',
 '  funnel for stages that narrow: Stage | number. scatter for two measures against each other: x-axis <name>, y-axis <name>, then Name | x | y.',
 '  heatmap for a value per day, one line each as 2026-09-01 | 45, or for a table of marks: a cols A, B, C line, then Row | x | - | x.',
 '  array for the cells of an algorithm, a row per step: Caption | 1, 3, 5, 7 | lo: 0, hi: 3 | 1..2, that is the values, the pointers by index and the cells to mark.',
 '  bracket for a knockout: each round is a line and its matches are indented under it, as Team 2 - 1 Team.',
 '- Kinds made for one subject are written the same way, and are the first choice whenever that subject comes up:',
 '  nutrition for what a day or a dish gives: Calories | 1850 kcal | of 2200, then Protein, Fat and Carbs each as Name | 132 g | of 150, then the meals as Breakfast: oatmeal with berries | 420 kcal | P 18 · F 12 · C 58.',
 '  recipe for a dish to cook: about 25 min | 2 servings | 650 kcal, then a line Ingredients with Name | amount | note indented under it, then a line Steps with Step | time | note under it; a line that starts with ! is what to mind at the step above.',
 '  facts for what a thing is at a glance (a document, a car, a product, a phone): file report.pdf | 42 pages | 1.8 MB for an attached file, then Label | value | note, with good, warn or bad as a last cell to mark a value.',
 '  outline for how a document is built: 1. Part | p. 3 | what it says, with its sub-parts indented under it.',
 '  checklist for what holds and what does not (claims checked, requirements, risks, an inspection, compatibility, packing): each row opens with [x] yes, [!] mind this, [-] no, [?] not known or [ ] still open, then Text | note; remarks are indented under a row.',
 '  changes for what became different (two versions of a document, settings, prices): Name | was -> now | note, with good or bad as a last cell.',
 '  matches for the games of a day or their results: 18:00 | Team A - Team B | tournament | note, or Team A 2 : 1 Team B once played; a last cell * marks the match to watch, and a line without bars names a day or a cup.',
 '  words for vocabulary: word | [how it is said] | meaning | example — its translation; a line without bars names a group of words.',
 '  gloss for a sentence taken apart: a line of its words parted by |, under it a line of what each means, then a line of what each is (case, tense, role), then = and the whole translation; put *stars* round the word to look at.',
 '  forms for conjugation and declension: a cols Present, Past line, then yo | hablo | hablé; the endings are marked by themselves, or put stars round the part that changes: *des* Tisches.',
 '  parts for a computer build, a kit or an estimate: Slot | part | what to know of it | price, with good, warn or bad as a last cell for whether it fits, and a last line total.',
 '  settings for setting up a phone, a system or an app: Settings > Battery > Power saving | on | note; write on or off for a switch, or the value to choose; a line without bars names a group.',
 '  route for a trip: Place | when or how long | what to see; a line indented under a place is the way on to the next (train | 2 h 50 min | 310 km), and a line Day 1 opens a day.',
 '  Choose the form by the subject. How something works or is made: a flowchart of the whole with its stages, and a chart for each curve or comparison in it. A document or a file the user sent: facts for what it is, outline for how it is built, then checklist, changes, timeline, metrics or bars for what it says, and a flowchart for the process it describes.',
 '  Food: nutrition, recipe, plan for a menu. Sport: matches, bracket, plan for a training week, metrics and heatmap for progress. Money: candlestick, waterfall, bars with a total, metrics, pie. A language: words, gloss, forms. A device: parts, settings, steps, checklist. A trip: route, plan by days, bars for the budget, checklist for packing. A repair: steps, ranges for the norms, parts for what to buy.',
 '  And by what the reader needs: a few key numbers are metrics, not a chart; a ranking is bars; a change over time is a line; steps to follow are steps; a schedule is plan or gantt.',
 '  Example:',
 '  ```mermaid',
 '  metrics',
 '    title Today',
 '    Calories | 1850 kcal | of 2200',
 '    Weight | 78.4 kg | -0.6 kg good | 80.1, 79.6, 79.2, 78.4',
 '  ```',
 '- For a website, landing page, app screen or any interface layout draw a wireframe, never a flowchart. It is the same mermaid block with first line wireframe (wireframe mobile for a phone screen),',
 '  then title <site name>, then the page sections from top to bottom: nav, hero, logos, features, cards, steps, stats, reviews, pricing, faq, cta, form, gallery, section, footer, each with its heading.',
 '  Indented under a section: text <paragraph>, button <label>, image or video, links A, B, C, fields A, B, and items as Title: short description.',
 '  Pricing items are Plan: price · feature · feature, mark the highlighted plan with * after its name. Write real texts in the language of the answer, not placeholders like "Heading".',
 '  Example:',
 '  wireframe',
 '    title north.studio',
 '    nav North',
 '      links Services, Cases, Pricing',
 '      button Contact us',
 '    hero Websites that bring clients',
 '      text Launch in 14 days with a forecast of leads',
 '      button Get a quote',
 '      image',
 '    features Why us',
 '      Speed: live in 14 days',
 '      Numbers: forecast before start',
 '    pricing Plans',
 '      Start: 900$ · Landing · 2 revisions',
 '      Business*: 1800$ · 10 pages · CRM',
 '    footer North',
 '      links Contacts, Privacy',
 '- Show files and folders as a files block, never as a text list, a table or an ASCII tree: whenever you show what is in a folder, the downloads, a project and its structure, or files you found or made.',
 '  Fence it like every diagram, as a ```mermaid block whose first line is files, then title <folder name>, path <full path>, then one line per entry: name | size | modified, the newest or most relevant first.',
 '  End a folder\'s name with / and give what it holds (12 items) when you know it; indent entries under their folder to show a tree. Copy sizes and dates from the listing (2.4 MB, 2026-09-27 14:05).',
 '  Show at most 30 entries and add a line more <number> for the rest. The app draws the folder with file icons and what takes the space, so after the block say only what stands out, don\'t list the files again.',
 '  Example, with its fence:',
 '  ```mermaid',
 '  files',
 '    title Downloads',
 '    path C:\\Users\\anna\\Downloads',
 '    report.pdf | 2.4 MB | 2026-09-27 14:05',
 '    photos/ | 48 items | 2026-09-20',
 '    setup.exe | 96 MB | 2026-09-18',
 '  ```',
 '  Keep labels short, wrap labels with punctuation in double quotes, never add style, classDef or colors, and never draw diagrams with ASCII art.',
 '- Write math as \\( … \\) inline and \\[ … \\] on its own line.',
 '- For a quotation use > with the quote itself and put the author on its own last line starting with —, for example > — Steve Jobs, Apple.',
 '  For notes, tips and warnings use > [!NOTE], > [!TIP] or > [!WARNING] instead of a plain quote.',
 '- Show column arithmetic (long multiplication, addition, subtraction, division) in a plain ``` block: digits right-aligned in columns (decimals aligned by the point),',
 '  the operator before the second number, a line of ─ under the operands and before the result, short comments after ← on the right. The app draws it as a clean worksheet.',
 '  A multi-step calculation can stay in one such block: a short title line, Label: value lines, each column right under its label, a blank line between steps,',
 '  a final Total: a + b = c line in the language of the answer, and a line of ─ between independent parts.',
].join('\n');
})();
