(() => {
'use strict';

// Renderer syntax and capabilities, shared at initialize → host.renderGuide.
// Whether and how to use these formats is the backend's choice, not frontend-owned agent policy.
window.RenderGuide = [
 'The renderer supports Markdown headings (##, ###), **bold**, lists, tables, images, and live editable charts and diagrams.',
 '- A picture is ![caption](image address), or [![caption](image address)](source page). Pictures on consecutive lines become one stack to leaf through. A video link alone on a line, [name · author · 4:40](https://www.youtube.com/watch?v=...), is shown as a card with its preview.',
 '- Charts and diagrams use fenced blocks with language mermaid and the diagram type on the first line:',
 '  flowchart TD or flowchart LR for processes and structures, sequenceDiagram for interactions, stateDiagram-v2 for states, erDiagram for database schemas, classDiagram for code structure,',
 '  xychart-beta for numeric series and curves (named series: line "Train" [...], bar "Revenue" [...]), pie for shares of one whole, quadrantChart for priority matrices, radar-beta for comparing options across criteria,',
 '  timeline for history and roadmaps, gantt for project plans, mindmap for breaking a topic down, gitGraph for branches and merges, sankey-beta for where money or traffic flows, treemap-beta for what a whole is made of,',
 '  candlestick for price history of crypto, stocks or any asset: optional `title BTC/USDT · 1D` and `ma 7` lines, then one line per candle: date, open, high, low, close, volume (plain numbers without thousands separators).',
 '  A flowchart block A["**Name**<br/>what happens in it"] shows a strong name and quiet detail. subgraph Name ... end groups stages; A -->|label| B labels an arrow.',
 '  A cycle linking the last step back to the first (E -->|next epoch| A) is drawn as a ring.',
 '  An xychart-beta also takes area "Name" [...], goal "Target" 2200 for a level to reach, zone "Normal" 60 --> 100 for a band of values, x-zone "Warm-up" 0 --> 10 for a stretch of the x-axis and mark "Early stop" 30 for a moment on it.',
 '  Several line rows draw several runs on one chart. y-axis "Loss" log enables a logarithmic scale; xychart-beta stacked stacks bars; xychart-beta horizontal turns them on their side. ISO dates on the x-axis (2026-09-01) position a line at its real dates.',
 '- The same mermaid block draws figures and plans that Mermaid has no type for. The first line is the type, then an optional title <text> line, then one row per line with its cells parted by |:',
 '  metrics for the few numbers that matter: Name | value with its unit, then any of: a change such as +4.2% or -0.6 kg (add good or bad after it to colour it), a target such as of 2200, a run of numbers for a small trend line, a note; good, bad or warn as a cell of its own marks the figure itself.',
 '  bars for a ranking, an estimate or a budget: Name | amount | note; a unit <unit> line names what the amounts are, and a last line total sums them up.',
 '  ranges for values against what is normal for them (test results, tyre pressure, pulse): Name | value with its unit | low-high, or <high, or >low.',
 '  plan for a week of training, a menu, a timetable or a board: each column is a line (Mon · Legs) and its cards are the lines indented under it, as Text | detail.',
 '  steps for a procedure someone follows (a repair, an installation, a setup): each step is a line, Step | time | tools; remarks are indented under it, and a remark that starts with ! is a warning. A step that starts with [x] is done.',
 '  waterfall for how a sum comes about: Start | 124, then signed changes such as Costs | -52, and Result | total.',
 '  funnel for stages that narrow: Stage | number. scatter for two measures against each other: x-axis <name>, y-axis <name>, then Name | x | y.',
 '  heatmap for a value per day, one line each as 2026-09-01 | 45, or for a table of marks: a cols A, B, C line, then Row | x | - | x.',
 '  array for the cells of an algorithm, a row per step: Caption | 1, 3, 5, 7 | lo: 0, hi: 3 | 1..2, that is the values, the pointers by index and the cells to mark.',
 '  bracket for a knockout: each round is a line and its matches are indented under it, as Team 2 - 1 Team.',
 '- Subject-specific kinds use the same row syntax:',
 '  nutrition for what a day or a dish gives: Calories | 1850 kcal | of 2200, then Protein, Fat and Carbs each as Name | 132 g | of 150, then the meals as Breakfast: oatmeal with berries | 420 kcal | P 18 · F 12 · C 58.',
 '  recipe for a dish to cook: about 25 min | 2 servings | 650 kcal, then a line Ingredients with Name | amount | note indented under it, then a line Steps with Step | time | note under it; a line that starts with ! is what to mind at the step above.',
 '  facts for what a thing is at a glance (a document, a car, a product, a phone): file report.pdf | 42 pages | 1.8 MB for an attached file, then Label | value | note, with good, warn or bad as a last cell to mark a value.',
 '  outline for how a document is built: 1. Part | p. 3 | what it says, with its sub-parts indented under it.',
 '  checklist for what holds and what does not (claims checked, requirements, risks, an inspection, compatibility, packing): each row opens with [x] yes, [!] mind this, [-] no, [?] not known or [ ] still open, then Text | note; remarks are indented under a row.',
 '  changes for what became different (two versions of a document, settings, prices): Name | was -> now | note, with good or bad as a last cell.',
 '  matches for the games of a day or their results: 18:00 | Team A - Team B | tournament | note, or Team A 2 : 1 Team B once played; a last cell * marks the match to watch, and a line without bars names a day or a cup.',
 '  words for vocabulary: word | [how it is said] | meaning | example — its translation; a line without bars names a group of words.',
 '  gloss for a sentence taken apart: a line of its words parted by |, under it a line of what each means, then a line of what each is (case, tense, role), then = and the whole translation; put *stars* round the word to look at.',
 '  forms for conjugation and declension: a cols Present, Past line, then yo | hablo | hablé; the endings are marked by themselves, or put stars round the part that changes: *des* Tisches.',
 '  parts for a computer build, a kit or an estimate: Slot | part | what to know of it | price, with good, warn or bad as a last cell for whether it fits, and a last line total.',
 '  settings for setting up a phone, a system or an app: Settings > Battery > Power saving | on | note; write on or off for a switch, or the value to choose; a line without bars names a group.',
 '  route for a trip: Place | when or how long | what to see; a line indented under a place is the way on to the next (train | 2 h 50 min | 310 km), and a line Day 1 opens a day.',
 '  Example:',
 '  ```mermaid',
 '  metrics',
 '    title Today',
 '    Calories | 1850 kcal | of 2200',
 '    Weight | 78.4 kg | -0.6 kg good | 80.1, 79.6, 79.2, 78.4',
 '  ```',
 '- Interface layouts are supported by a mermaid block with first line wireframe (wireframe mobile for a phone screen),',
 '  then title <site name>, then the page sections from top to bottom: nav, hero, logos, features, cards, steps, stats, reviews, pricing, faq, cta, form, gallery, section, footer, each with its heading.',
 '  Indented under a section: text <paragraph>, button <label>, image or video, links A, B, C, fields A, B, and items as Title: short description.',
 '  Pricing items are Plan: price · feature · feature; * after the plan name highlights it.',
 '  Example:',
 '  wireframe',
 '    title north.studio',
 '    nav North',
 '      links Services, Cases, Pricing',
 '      button Contact us',
 '    hero Websites that bring clients',
 '      text Launch in 14 days with a forecast of leads',
 '      button Get a quote',
 '      image',
 '    features Why us',
 '      Speed: live in 14 days',
 '      Numbers: forecast before start',
 '    pricing Plans',
 '      Start: 900$ · Landing · 2 revisions',
 '      Business*: 1800$ · 10 pages · CRM',
 '    footer North',
 '      links Contacts, Privacy',
 '- A files block displays files and folders with icons and sizes.',
 '  Syntax: a ```mermaid block whose first line is files, then title <folder name>, path <full path>, then one line per entry: name | size | modified.',
 '  A folder name ends with / and can include an item count (12 items); indented entries form a tree. Sizes and dates accept forms such as 2.4 MB and 2026-09-27 14:05.',
 '  A line more <number> indicates additional entries.',
 '  Example, with its fence:',
 '  ```mermaid',
 '  files',
 '    title Downloads',
 '    path C:\\Users\\anna\\Downloads',
 '    report.pdf | 2.4 MB | 2026-09-27 14:05',
 '    photos/ | 48 items | 2026-09-20',
 '    setup.exe | 96 MB | 2026-09-18',
 '  ```',
 '  Diagram labels with punctuation can be double-quoted. style and classDef directives are ignored; diagram colors are renderer-controlled.',
 '- Math syntax: \\( … \\) inline and \\[ … \\] on its own line.',
 '- Quotations use >; an attribution is a final line starting with —, for example > — Steve Jobs, Apple.',
 '  Callouts use > [!NOTE], > [!TIP] or > [!WARNING].',
 '- Column arithmetic (long multiplication, addition, subtraction, division) renders as a worksheet in a plain ``` block: digits right-aligned in columns (decimals aligned by the point),',
 '  the operator before the second number, a line of ─ under the operands and before the result, short comments after ← on the right. The app draws it as a clean worksheet.',
 '  A multi-step calculation can stay in one such block: a short title line, Label: value lines, each column right under its label, a blank line between steps,',
 '  a final Total: a + b = c line, and a line of ─ between independent parts.',
].join('\n');
})();
