#include "tooltext.h"

#include <utility>

QVariantMap ToolText::describe(const QString &name, const QString &json, bool known) const
{
    const toolcard::Info info = toolcard::describe(name, json, known);
    const auto lines = [](const toolcard::Lines &side) {
        return QVariantMap{{QStringLiteral("shown"), side.shown}, {QStringLiteral("more"), side.more}};
    };
    return {{QStringLiteral("kind"), info.kind},
            {QStringLiteral("title"), info.title},
            {QStringLiteral("path"), info.path},
            {QStringLiteral("code"), info.code},
            {QStringLiteral("text"), info.text},
            {QStringLiteral("url"), info.url},
            {QStringLiteral("removed"), info.removed},
            {QStringLiteral("added"), info.added},
            {QStringLiteral("summary"), info.summary},
            {QStringLiteral("link"), info.link},
            {QStringLiteral("removedLines"), lines(info.removedLines)},
            {QStringLiteral("addedLines"), lines(info.addedLines)}};
}

// Generated by qt_add_qml_module for OpenGhost.ToolCalls (ToolText above).
void qml_register_types_OpenGhost_ToolCalls();

void registerToolCallsTypes()
{
    static bool done = false;
    if (!std::exchange(done, true))
        qml_register_types_OpenGhost_ToolCalls();
}
